name: Auto-close PRs and Issues

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  auto-close:
    runs-on: ubuntu-latest
    steps:
      - name: Close new PRs/issues
        uses: actions/github-script@v7
        with:
          script: |
            const isPR = !!context.payload.pull_request;
            const number = isPR ? context.payload.pull_request.number : context.payload.issue.number;

            // Close the issue or PR
            if (isPR) {
              await github.rest.pulls.update({
                ...context.repo,
                pull_number: number,
                state: 'closed'
              });
            } else {
              await github.rest.issues.update({
                ...context.repo,
                issue_number: number,
                state: 'closed'
              });
            }

            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: number,
              body: `Thank you for your contribution. The last day to participate in the hackathon was 1st June 2025. We are no longer accepting new issues or pull requests. We will be announcing the winners soon.`
            });
